// <auto-generated />
using EFcodefirstapproach.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFcodefirstapproach.Migrations
{
    [DbContext(typeof(MtrDBContext))]
    partial class MtrDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFcodefirstapproach.Models.Dtr", b =>
                {
                    b.Property<int>("MtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MtId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MtrName");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PowerStatus");

                    b.Property<int>("current")
                        .HasColumnType("int");

                    b.Property<int>("voltage")
                        .HasColumnType("int");

                    b.HasKey("MtId");

                    b.ToTable("Dtrs");
                });
#pragma warning restore 612, 618
        }
    }
}
